### ISSUE TITLE
Chinese Dependency Parser  Compile error

### ISSUE THREAD

**Issue by zhangmeishan** [SUTDNLP/ZPar#1]
python configure.py chinese depparser
cmake .
make

Scanning dependencies of target chinese.depparser.parser
[  5%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/libs/reader.cpp.o
[ 10%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/libs/writer.cpp.o
[ 15%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/libs/options.cpp.o
[ 20%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/libs/linguistics/lemma.cpp.o
[ 25%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/libs/linguistics/conll.cpp.o
[ 30%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/libs/learning/dbn.cpp.o
[ 35%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/common/depparser/implementations/arceager/depparser.cpp.o
[ 40%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/common/depparser/implementations/arceager/depparser_weight.cpp.o
[ 45%] Building CXX object CMakeFiles/chinese.depparser.parser.dir/src/common/depparser/main.cpp.o
/home/mason/workspace/ZPar/src/common/depparser/main.cpp: In function ‘void process(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, long unsigned int, bool, const string&, bool, const string&)’:
/home/mason/workspace/ZPar/src/common/depparser/main.cpp:85:23: error: cannot convert ‘std::istream {aka std::basic_istream<char>}’ to ‘bool’ in assignment
       bReadSuccessful = ( (_is) >> input_conll );
                       ^
/home/mason/workspace/ZPar/src/common/depparser/main.cpp:138:26: error: cannot convert ‘std::istream {aka std::basic_istream<char>}’ to ‘bool’ in assignment
          bReadSuccessful = ( (_is) >> input_conll );
                          ^
CMakeFiles/chinese.depparser.parser.dir/build.make:254: recipe for target 'CMakeFiles/chinese.depparser.parser.dir/src/common/depparser/main.cpp.o' failed
make[2]: **\* [CMakeFiles/chinese.depparser.parser.dir/src/common/depparser/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/chinese.depparser.parser.dir/all' failed
make[1]: **\* [CMakeFiles/chinese.depparser.parser.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by LeonCrashCode** [comment]
There is no compile error in my workspace. I guess you can check g++ version (4.9.2 or higher).
also, you can try

 ./configure
./configure.py chinese depparser
make

**Comment by zhangmeishan** [comment]
Add explicit type conversions, then the code will be fine.
